export { default as Hero} from './Hero'
export { default as Services} from './Services'
export { default as About} from './About'
export { default as Affiliates} from './Affiliates'
export { default as Contact} from './Contact'
export { default as Materials} from './Materials'